import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>WebApp Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="max-w-6xl mx-auto">
        <div className="flex flex-col justify-center max-w-4xl py-64 mx-auto">
          <h1 className="font-bold text-7xl">Build. Launch. Grow.</h1>
          <p className=" text-2xl py-2 text-gray-500">
            Utility crafts award-winning mobile experiences driven by strategy,
            design and technology.
          </p>
          <div className="font-semibold text-2xl pt-10">See Our Work</div>
        </div>
      </section>
    </>
  );
}
